name: web-app
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - pygraphviz=1.9
  - pip:
    - collections
    - graphviz==0.20.1
    - matplotlib==3.7.1
    - numpy==1.24.2
    - pandas==1.5.3
    - pydot==1.4.2
    
